// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID        int32              `json:"id"`
	SiteID    string             `json:"site_id"`
	EventType string             `json:"event_type"`
	Path      string             `json:"path"`
	UserID    string             `json:"user_id"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
}