// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
  site_id, event_type, path, user_id, "timestamp"
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id
`

type CreateEventParams struct {
	SiteID    string             `json:"site_id"`
	EventType string             `json:"event_type"`
	Path      string             `json:"path"`
	UserID    string             `json:"user_id"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (int32, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.SiteID,
		arg.EventType,
		arg.Path,
		arg.UserID,
		arg.Timestamp,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getSiteStats = `-- name: GetSiteStats :one
SELECT
    COALESCE(COUNT(id), 0)::bigint AS total_views,
    COALESCE(COUNT(DISTINCT user_id), 0)::bigint AS unique_users
FROM events
WHERE
    site_id = $1
    AND event_type = 'page_view'
    AND "timestamp" >= $2
    AND "timestamp" < $3
`

type GetSiteStatsParams struct {
	SiteID     string             `json:"site_id"`
	Timestamp  pgtype.Timestamptz `json:"timestamp"`
	Timestamp2 pgtype.Timestamptz `json:"timestamp_2"`
}

type GetSiteStatsRow struct {
	TotalViews  int64 `json:"total_views"`
	UniqueUsers int64 `json:"unique_users"`
}

func (q *Queries) GetSiteStats(ctx context.Context, arg GetSiteStatsParams) (GetSiteStatsRow, error) {
	row := q.db.QueryRow(ctx, getSiteStats, arg.SiteID, arg.Timestamp, arg.Timestamp2)
	var i GetSiteStatsRow
	err := row.Scan(&i.TotalViews, &i.UniqueUsers)
	return i, err
}

const getTopPaths = `-- name: GetTopPaths :many
SELECT
    path,
    COUNT(id) AS views
FROM events
WHERE
    site_id = $1
    AND event_type = 'page_view'
    AND "timestamp" >= $2
    AND "timestamp" < $3
GROUP BY path
ORDER BY views DESC
LIMIT 10
`

type GetTopPathsParams struct {
	SiteID     string             `json:"site_id"`
	Timestamp  pgtype.Timestamptz `json:"timestamp"`
	Timestamp2 pgtype.Timestamptz `json:"timestamp_2"`
}

type GetTopPathsRow struct {
	Path  string `json:"path"`
	Views int64  `json:"views"`
}

func (q *Queries) GetTopPaths(ctx context.Context, arg GetTopPathsParams) ([]GetTopPathsRow, error) {
	rows, err := q.db.Query(ctx, getTopPaths, arg.SiteID, arg.Timestamp, arg.Timestamp2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopPathsRow
	for rows.Next() {
		var i GetTopPathsRow
		if err := rows.Scan(&i.Path, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}